package formats.sdf.vocabulary

import org.apache.jena.rdf.model.ResourceFactory

object KAIROS {
  val PREFIX = "kairos"
  val URI = "https://kairos-sdf.s3.amazonaws.com/context/kairos/"

  // Properties
  val achieves = ResourceFactory.createProperty(URI + "achieves")
  val after = ResourceFactory.createProperty(URI + "after")
  val aka = ResourceFactory.createProperty(URI + "aka")
  val before = ResourceFactory.createProperty(URI + "before")
  val boundingBox = ResourceFactory.createProperty(URI + "boundingBox")
  val childId = ResourceFactory.createProperty(URI + "childID")
  val comment = ResourceFactory.createProperty(URI + "comment")
  val confidence = ResourceFactory.createProperty(URI + "confidence")
  val contained = ResourceFactory.createProperty(URI + "contained")
  val container = ResourceFactory.createProperty(URI + "container")
  val endTime = ResourceFactory.createProperty(URI + "endTime")
  val entityRelations = ResourceFactory.createProperty(URI + "entityRelations")
  val entityTypes = ResourceFactory.createProperty(URI + "entityTypes")
  val entityTypes_AND = ResourceFactory.createProperty(URI + "entityTypes_AND")
  val entityTypes_OR = ResourceFactory.createProperty(URI + "entityTypes_OR")
  val flags = ResourceFactory.createProperty(URI + "flags")
  val keyframes = ResourceFactory.createProperty(URI + "keyframes")
  val length = ResourceFactory.createProperty(URI + "length")
  val maxDuration = ResourceFactory.createProperty(URI + "maxDuration")
  val mediaType = ResourceFactory.createProperty(URI + "mediaType")
  val minDuration = ResourceFactory.createProperty(URI + "minDuration")
  val offset = ResourceFactory.createProperty(URI + "offset")
  val order = ResourceFactory.createProperty(URI + "order")
  val overlaps = ResourceFactory.createProperty(URI + "overlaps")
  val parentIds = ResourceFactory.createProperty(URI + "parentIDs")
  val participants = ResourceFactory.createProperty(URI + "participants")
  val primitives = ResourceFactory.createProperty(URI + "primitives")
  val privateData = ResourceFactory.createProperty(URI + "privateData")
  val provenance = ResourceFactory.createProperty(URI + "provenance")
  val provenanceData = ResourceFactory.createProperty(URI + "provenanceData")
  val reference = ResourceFactory.createProperty(URI + "reference")
  val refvar = ResourceFactory.createProperty(URI + "refvar")
  val relations = ResourceFactory.createProperty(URI + "relations")
  val relationObject = ResourceFactory.createProperty(URI + "relationObject")
  val relationPredicate = ResourceFactory.createProperty(URI + "relationPredicate")
  val relationSubject = ResourceFactory.createProperty(URI + "relationSubject")
  val requires = ResourceFactory.createProperty(URI + "requires")
  val role = ResourceFactory.createProperty(URI + "role")
  val roleName = ResourceFactory.createProperty(URI + "roleName")
  val schemas = ResourceFactory.createProperty(URI + "schemas")
  val sdfVersion = ResourceFactory.createProperty(URI + "sdfVersion")
  val slots = ResourceFactory.createProperty(URI + "slots")
  val startTime = ResourceFactory.createProperty(URI + "startTime")
  val steps = ResourceFactory.createProperty(URI + "steps")
  val `super` = ResourceFactory.createProperty(URI + "super")
  val ta2 = ResourceFactory.createProperty(URI + "ta2")
  val template = ResourceFactory.createProperty(URI + "template")
  val values = ResourceFactory.createProperty(URI + "values")
}
